### ISSUE TITLE
Mido Hayama

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_assets#104]
## thumbnail_url
![thumbnail_url](https://user-images.githubusercontent.com/44924233/120357105-0be7dc80-c340-11eb-8c71-dea886105ce7.jpg)

## source_url
https://bowlroll.net/file/162201

## download_action
```python
bowlroll('https://bowlroll.net/file/162201')
```

## import_action
```python
unzip(encoding='cp932'); import_pmx('MMD_v1.6.4(2021.06.01fix)ElsieEstuary/★MMDモデル/[V07]cosplayHayamaMido(feat葉山みど).pmx',scale=0.08)
```

## aliases
| en | Mido Hayama |
|--|--|
| ja | 葉山みど |

## note
★ テクスチャエラーで紫になるので、その他>MMD Display > Toon TextureをOFFにしてください
　To fix texture error (when model becomes purple)
  Misc > MMD Display > Toon Texture OFF

**Comment by listelin** [comment]
```
location: <unknown location>:-1
エラー: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 219, in execute
    ImportActionExecutor.execute_import_action(asset, content.filepath if content is not None else None)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 394, in execute_import_action
    **functions
  File "<source>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 198, in unzip
    info.filename = info.orig_filename.encode(orig_codec).decode(encoding)
UnicodeDecodeError: 'cp932' codec can't decode byte 0x84 in position 49: illegal multibyte sequence

location: <unknown location>:-1
```
TO FIX: asset_search/actions.py Line 198

```
-                info.filename = info.orig_filename.encode(orig_codec).decode(encoding)
+                info.filename = info.orig_filename.encode(orig_codec).decode(encoding,'ignore')
```

**Comment by listelin** [comment]
Fixed in v0.6.6
