### ISSUE TITLE
Super Pochako 3.0 (Super Chubby Girl)

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_assets#124]
## thumbnail_url
![thumbnail_url](https://user-images.githubusercontent.com/44924233/120459339-12736400-c3d3-11eb-9a0d-8caaf58b2d27.jpg)

## source_url
https://bowlroll.net/file/245178

## download_action
```python
bowlroll('https://bowlroll.net/file/245178')
```

## import_action
```python
unzip(encoding='cp932'); import_pmx('すーぱーぽちゃ子（Ver.3.0）/すーぱーぽちゃ子（Ver.3.0）.pmx',scale=0.08)
```

## aliases
| en | Super Pochako (Super Chubby Girl) |
|--|--|
| ja | すーぱーぽちゃ子（Ver.3.0） |

**Comment by listelin** [comment]
```
do: MMD_UUUNYAA_TOOLS_OT_asset_download, 00124
Starting new HTTPS connection (1): bowlroll.net:443
https://bowlroll.net:443 "GET /file/245178 HTTP/1.1" 200 None
Resetting dropped connection: bowlroll.net
https://bowlroll.net:443 "POST /api/file/245178/download-check HTTP/1.1" 403 None
Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\cache.py", line 214, in _fetch
    response = self.url_resolver.resolve(task.url)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\url_resolvers.py", line 21, in resolve
    return DownloadActionExecutor.execute_action(url)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 174, in execute_action
    return eval(  # pylint: disable=eval-used
  File "<string>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 95, in bowlroll
    response.raise_for_status()
  File "C:\blender\blender-2.93.0-windows64\2.93\python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bowlroll.net/api/file/245178/download-check
done: Super Pochako 3.0 (Super Chubby Girl), 00124, State.FAILED, 9660affbdd67bebc9901b7b2da9edee38b4c646f
_save_contents: 104 to C:\tmp\mmd_uuunyaa_tools_cache\contents.json
```
same error in 2.9.2

**Comment by UuuNyaa** [comment]
このアセットをダウンロードするためにはbowlrollへのログインが必須なようです。
ログイン必須のアセットはしばらくサポート対象外とさせてください。

Maybe you need to log in to bowlroll to download this asset.
Assets that require login will not be supported for a while.
