### ISSUE TITLE
Pojio type sister

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_assets#129]
## thumbnail_url
![thumbnail_url](https://user-images.githubusercontent.com/44924233/120468347-122b9680-c3dc-11eb-8d25-6c5eb0979e7a.jpg)

## source_url
https://bowlroll.net/file/229580

## download_action
```python
bowlroll('https://bowlroll.net/file/229580')
```

## import_action
```python
unzip(encoding='cp932'); import_pmx('ぽじお式シスター/シスター.pmx',scale=0.08)
```

## aliases
| en | Pojio type sister |
|--|--|
| ja | ぽじお式シスター |

## note

**Comment by listelin** [comment]
```
エラー: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\operators.py", line 79, in execute
    cat_asset_json.fetch_asset(session, self.repo, self.issue_number)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\externals\blender_mmd_assets\cat_asset_json.py", line 198, in fetch_asset
    return to_asset(
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\externals\blender_mmd_assets\cat_asset_json.py", line 137, in to_asset
    line = block['lines'][0]
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by UuuNyaa** [comment]
"note"セクションに続いて空行がないことが問題の原因でした。
空行がなくても読込できるように修正します。

The lack of a blank line follow the Note section was the cause of the problem.
I will fix it so that it can be read without a blank line.
