### ISSUE TITLE
Conqueror

### ISSUE THREAD

**Issue by Wakewakameuma** [UuuNyaa/blender_mmd_assets#194]
## thumbnail_url
![thumbnail_url](https://file-image-storage.bowlroll.net/storage/eyJhbGciOiJIUzUxMiJ9.eyJhY3Rpb24iOiJTSE9XIiwicmV2aXNpb24iOjIyMTk3LCJidWNrZXQiOiJmaWxlLWltYWdlIiwicmVzb3VyY2UtaWQiOiIxOTA2NjQifQ.5490FK8kEq9jJEvkLNDdekbAiu3lOJszdZ9z2L978M6dnoM48V4sMhQx4ny_aydPQhejoSjEE9OCgGo8IfhmSA)

## source_url
https://bowlroll.net/file/190664

## download_action
```python
bowlroll('https://bowlroll.net/file/190664')
```

## import_action
```python
un7zip(); import_vmd('IA_Conqueror_Motion/IA_Conqueror_light_version.vmd',scale=0.08)
```

## aliases
| en | Conqueror IA |
|--|--|
| ja | Conqueror IA |

**Comment by listelin** [comment]
- Aliasesに　”|"が入っているのでディレクトリ作成エラーになります。

多分このように修正すればいいのではないでしょうか。
| en | Conqueror IA |
| ja | Conqueror IA |

- また、分かっているかもしれませんが登録時は以下のように確認します。
1. UuuNyaaアセットオペレーターで、クエリを{'state': 'open'}　にしてオープン中のものを全て取得するようにする
　（デフォルトでは、Official、Milestone:  public assetのみを取得）
2. UuuNyaaアセットオペレーターで、(1)アセットJSONをクエリで更新でダウンロード、(2)アセットJSONをリロードでBlenderに反映
3. 検索してうまくいくか確認

---
エラー: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 221, in execute
    ImportActionExecutor.execute_import_action(asset, content.filepath if content is not None else None)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 394, in execute_import_action
    exec(  # pylint: disable=exec-used
  File "<source>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 204, in unzip
    zip_file.extract(info, path=asset_path, pwd=pwd)
  File "C:\blender\blender-3.0.0-windows-x64\3.0\python\lib\zipfile.py", line 1616, in extract
    return self._extract_member(member, path, pwd)
  File "C:\blender\blender-3.0.0-windows-x64\3.0\python\lib\zipfile.py", line 1679, in _extract_member
    os.makedirs(upperdirs)
  File "C:\blender\blender-3.0.0-windows-x64\3.0\python\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\blender\blender-3.0.0-windows-x64\3.0\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: 'C:\\bData\\assets_un\\MOTION_MMD\\00194.Conqueror | IA'

location: <unknown location>:-1

**Comment by Wakewakameuma** [comment]
ありがとうございます
困っておりました
修正していきます

**Comment by listelin** [comment]
修正してもなぜか反映されないですね
バグかもしれません。

本体のissueで確認してみます。

普通はアセット追加でこんな面倒にはならないのですが

**Comment by Wakewakameuma** [comment]
ありがとうございます
実はまだ自分の環境で確認できずにおりまして
出来次第Public Assetに変更し
ラベルにOfficialを追加したいと思います
mmd_tools便利ですね

**Comment by listelin** [comment]
このエントリの内容を変更した場合、通常は、UuuNyaaアセットオペレーターで、

　(1)アセットJSONをクエリで更新でダウンロード
　(2)アセットJSONをリロードでBlenderに反映

これだけやればいいはずなのですが、なぜか今回(2)がうまくいかない事象があって（ローカルのアセットjsonは”|"なしに更新されているのに同じエラーになる）、プリファレンスのアセットキャッシュファイルの削除とかblenderの再起動とか色々やってるうちに解消しました

問題があって解決しないようなら遠慮なく質問してください

**Comment by Wakewakameuma** [comment]
ダウンロードして動作確認までできたので
ラベルとマイルストーンを編集しようと思ったのですが
できませんでした…

GitHubの操作における質問なのですが
LabelsとMilestaoneが変更できなくなるような状態というのは
何が原因なのでしょうか

（試しに自身でプロジェクトをテストで作成しissueを追加したところ、そちらでは問題なく変更できました）

**Comment by listelin** [comment]
あ！すみません。ラベル、マイルストーン変更は権限がないとできないんでした

Uuunyaaさんに依頼しますね

**Comment by Wakewakameuma** [comment]
ありがとうございます！

**Comment by UuuNyaa** [comment]
@Wakewakameuma @listelin

アセットを追加していただきありがとうございます。
@Wakewakameuma さんをこのリポジトリの協力者として招待しました。

Thanks for adding assets.
I have invited @Wakewakameuma to be a collaborator in this repository.
