### ISSUE TITLE
mob guy

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_assets#95]
## thumbnail_url
![thumbnail_url](https://user-images.githubusercontent.com/44924233/120064885-79c6a680-c0a9-11eb-81fa-15a2820a3125.png)

## source_url
https://fantia.jp/posts/425699

## download_action
```python
uploader('https://ux.getuploader.com/siyu_custom/download/6',password='mobutinpo')
```

## import_action
```python
unzip(encoding='cp932'); import_pmx('【しゆ式竿役モブ男】/竿役モブ男.pmx',scale=0.08)
```

## aliases
| en | mob guy |
|--|--|
| ja | 竿役モブ男 |

**Comment by listelin** [comment]
https://ux.getuploader.com:443 "POST /siyu_custom/download/6 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\cache.py", line 214, in _fetch
    response = self.url_resolver.resolve(task.url)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\url_resolvers.py", line 21, in resolve
    return DownloadActionExecutor.execute_action(url)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 178, in execute_action
    **functions
  File "<string>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 147, in uploader
    raise ValueError(error_message)
ValueError: Failed to download assets from uploader.jp. uploader.jp response format may have changed.
done: mob guy, 00095, State.FAILED, 76a4f71e565698b19b3aa80b8bfce69e3960fbee

**Comment by UuuNyaa** [comment]
v0.6.3 supports age confirmation on uploader.jp
