### ISSUE TITLE
Hacka Doll No. 3 Futanari

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_assets#98]
## thumbnail_url
![thumbnail_url](https://user-images.githubusercontent.com/44924233/120324390-87866100-c321-11eb-8e17-178711aabcc0.jpg)

## source_url
https://ecchi.iwara.tv/videos/k6r2wumvpiq8yvzw

## download_action
```python
uploader('https://ux.getuploader.com/siyu_custom/download/6',password='hakka3chinchinn')
```

## import_action
```python
unzip(encoding='cp932',password='hakka3chinchinn'); import_pmx('おんだ式ハッカドール3号_ふたなり包茎_Ver102/おんだ式ハッカドール3号_ふたなり包茎_Ver102a_顔オリ.pmx',scale=0.08)
```

## aliases
| en | おんだ式ハッカドール3号 ふたなり包茎 |
|--|--|
| ja | Onda Type Hacka Doll No. 3: Futanari Foreskin |

**Comment by listelin** [comment]
エラー: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\panels.py", line 215, in execute
    ImportActionExecutor.execute_import_action(asset, content.filepath if content is not None else None)
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 392, in execute_import_action
    **functions
  File "<source>", line 1, in <module>
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\actions.py", line 199, in unzip
    zip_file.extract(info, path=asset_path, pwd=password)
  File "C:\blender\blender-2.92.0-windows64\2.92\python\lib\zipfile.py", line 1619, in extract
    return self._extract_member(member, path, pwd)
  File "C:\blender\blender-2.92.0-windows64\2.92\python\lib\zipfile.py", line 1689, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "C:\blender\blender-2.92.0-windows64\2.92\python\lib\zipfile.py", line 1486, in open
    raise TypeError("pwd: expected bytes, got %s" % type(pwd).__name__)
TypeError: pwd: expected bytes, got str

location: <unknown location>:-1

**Comment by listelin** [comment]
以下の修正で動作することを確認しました

asset_search/actions.py line 199
-                zip_file.extract(info, path=asset_path, pwd=password)
+                zip_file.extract(info, path=asset_path, pwd=password.encode())

**Comment by UuuNyaa** [comment]
v0.6.5 Fix zip extracting with password.

**Comment by listelin** [comment]
I have confirmed that version 0.6.5 works fine.
